# Basic
title: Jeney
subtitle: Android Developer
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: coding 日本語 longboard
creator: <a href="">@Jeney</a>

# url: "http://vno.onevcat.com"
url: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: jeneyloo
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: 
    twitter: 
    gplus: 
    mail: 
    # weibo: onevcat
    # github: onevcat
    # twitter: onevcat
    # gplus: 107108267983477358170
    # mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
